name: carepetsapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.8
  image_picker: ^0.8.4+9
  firebase_storage: ^10.2.7
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.4
  geolocator: ^8.2.0
  geocoding: ^2.0.2
  uuid: ^3.0.6
  image: ^3.1.3
  animator: ^3.1.0
  path_provider: ^2.0.9
  timeago: ^3.2.2
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_launcher_icons: "^0.9.2"
  open_mail_app: ^0.4.5
  flutter_phone_direct_caller: ^2.1.1
  dropdown_button2: ^1.0.0
  native_video_view: ^1.0.5
  flutter_local_notifications: ^9.4.1
  firebase_messaging: ^11.4.0
  firebase_core: ^1.13.1
  overlay_support: ^1.2.1
  http: ^0.13.4
  add_2_calendar: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Retroica
      fonts:
        - asset: assets/fonts/Retroica.ttf
    - family: Saudagar
      fonts:
        - asset: assets/fonts/Saudagar.ttf
    - family: Kenyan
      fonts:
        - asset: assets/fonts/kenyan coffee bd it.ttf
        - asset: assets/fonts/kenyan coffee bd.ttf
        - asset: assets/fonts/kenyan coffee rg it.ttf
        - asset: assets/fonts/kenyan coffee rg.ttf
    
        
  assets:
    - assets/images/
    - assets/videos/